name: CTEM Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  ctem-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Install GitLeaks manually
      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      # ✅ Run GitLeaks and generate SARIF
      - name: Run GitLeaks scan
        run: |
          gitleaks detect --source . --report-format sarif --report-path results.sarif || true

      # ✅ Upload SARIF to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      # ✅ Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # ✅ Run Trivy and save results to file
      - name: Run Trivy scan
        run: trivy fs . --format json --output trivy-results.json --exit-code 0

      # ✅ Run memory_tracker.py
      - name: Run memory tracker
        run: python scripts/memory_tracker.py

      # ✅ Upload dashboard JSON output (for CI preview / download)
      - name: Upload data.json for dashboard
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-data
          path: dashboard/data.json

  deploy-dashboard:
    needs: ctem-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Copy dashboard to deployment folder
        run: |
          mkdir -p public
          cp dashboard/data.json public/
          cp -r dashboard/templates/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
