name: CTEM Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Create scans directory
        run: mkdir -p scans

      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

      - name: Run Trivy scan
        run: trivy fs --format json --output scans/trivy.json ./app

      - name: Compare with exposure memory and update
        run: python3 scripts/compare.py

      - name: Generate dashboard data
        run: python3 scripts/generate_dashboard.py

      - name: Alert on repeated vulnerabilities
        run: python3 scripts/alert.py
