name: CTEM Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --config-path .gitleaks.toml --report-format json --report-path scans/gitleaks.json

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./app
          format: json
          output: scans/trivy.json

      - name: Compare with exposure memory and update
        run: python3 scripts/compare.py

      - name: Generate dashboard data
        run: python3 scripts/generate_dashboard.py

      - name: Alert on repeated vulnerabilities
        run: python3 scripts/alert.py
