name: CTEM Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ctem-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          args: detect --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif --log-level=debug --log-opts=-1

      - name: Upload GitLeaks SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: gitleaks

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      - name: Run Trivy vulnerability scan
        run: trivy fs . --exit-code 0 --format json --output trivy-results.json

      - name: Upload Trivy results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json

      - name: Run CTEM memory tracker
        run: python scripts/memory_tracker.py

      - name: Upload SQLite DB
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ctem-memory
          path: memory/memory.db
