name: CTEM Pipeline Security

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # GitLeaks - secrets scanning (non-fatal)
    - name: Run GitLeaks scan
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    # Trivy - CVEs and Misconfig scan with install workaround
    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y

    - name: Run Trivy file system scan
      run: trivy fs . --exit-code 0 --format table --output trivy-results.txt

    # Memory Comparison Script
    - name: Run Vulnerability Memory Tracker
      run: python memory_tracker.py
      working-directory: ./scripts

    # Upload GitLeaks SARIF report to GitHub Security tab
    - name: Upload GitLeaks SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
      continue-on-error: true

    # Upload Trivy result artifact
    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.txt

    # Upload SQLite memory DB as artifact
    - name: Upload vulnerability memory DB
      uses: actions/upload-artifact@v4
      with:
        name: vuln-memory
        path: ./scripts/vuln_memory.db
